### ISSUE TITLE
dir_util.py AttributeError: 'dict' object has no attribute 'add'

### ISSUE THREAD

**Issue by phil622** [franciscozorrilla/thesis_pipeline#167]
when i run metagem with -t binReassemble
it return the error ：
_path_created.add(abs_head)
AttributeError: 'dict' object has no attribute 'add'
but in dir_util.py the _path_created is identified as set
why it happening

**Comment by franciscozorrilla** [comment]
hey phil! sorry for the delayed response, I just had my PhD defense 🤓 
It is difficult to determine what could be going wrong, but based on this message it seems like maybe some expected file or folder is missing. Could you provide more details about your dataset, the commands used, and a full error log?

best,
Francisco

**Comment by phil622** [comment]
Congratulations！
By the way, I am also in the process of pursuing a phD.

Here is the full error log:
"
Traceback (most recent call last):
  File "~/envs/metawrap/bin/spades.py", line 874, in main
    used_K = spades_logic.run_spades(tmp_configs_dir, bin_home, spades_cfg, dataset_data, ext_python_modules_home, log)
  File "~/envs/metawrap/share/spades-3.13.0-0/share/spades/spades_pipeline/spades_logic.py", line 311, in run_spades
    run_iteration(configs_dir, execution_home, cfg, log, K, None, False)
  File "~/envs/metawrap/share/spades-3.13.0-0/share/spades/spades_pipeline/spades_logic.py", line 188, in run_iteration
    dir_util.copy_tree(os.path.join(configs_dir, "debruijn"), dst_configs, preserve_times=False)
  File "~/envs/metagem/lib/python3.10/site-packages/setuptools/_distutils/dir_util.py", line 146, in copy_tree
    mkpath(dst, verbose=verbose)
  File "~/envs/metagem/lib/python3.10/site-packages/setuptools/_distutils/dir_util.py", line 82, in mkpath
    _path_created.add(abs_head)
AttributeError: 'dict' object has no attribute 'add'
"

It seems like a conflict between setuptools and spades. 
In seuptools dir_util.py file, it identity "_path_created = set()", however it also a global variable in spades_logic.py, identity as dir_util._path_created = {}
so it return as 'dict' object has no attribute 'add'
I just change the "dir_util._path_created = {}" to "dir_util._path_created = set()" in spades_logic.py, and it works, but i dont know if it can influent my finally result or not.
Thanks a log.

**Comment by franciscozorrilla** [comment]
Great that you managed to find a fixaround, and good luck with your PhD projects!
Happy to help with any other issues and thanks for reporting this error.

Best,
Francisco
