### ISSUE TITLE
[Bug]: Issue with running MetaGem with Slurm job handler

### ISSUE THREAD

**Issue by ecairns62** [franciscozorrilla/thesis_pipeline#170]
Hello. 

I'm trying to run MetaGEM on my university's HPC, but running into some issues with the Slurm job handler. This error 

- sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified
Error submitting jobscript (exit code 1):

[utput=metagem_50011685.log](https://github.com/user-attachments/files/17961245/utput.metagem_50011685.log)

Is stopping me from going any further. I have tried to edit the cluster_config.json file to resolve it, but no luck. I'm unsure whether it is clashing with the slurm submission file that also sets out cluster values like this: 
"
#!/bin/bash -l
#SBATCH -D ./                          # Set wd
#SBATCH --export=ALL                   # Copy current enviroment
#SBATCH -J Metagem1DNA                 # Job name
#SBATCH -p nodes                       # Specify partition (e.g., compute, batch)
#SBATCH -N 1                           # Number of nodes
#SBATCH -n 4                           # Number of tasks            
#SBATCH -t 2:00:00                     # Time limit hrs:min:sec
#SBATCH -output=metagem_%j.log         # Standard output and error log

# Run MetaGem
yes | bash metaGEMedit.sh -t fastp -j 2 -c 4 -m 10 -h 2

yes | bash metaGEMedit.sh -t qfilterVis 
"

I have ran the script locally with no issues. 

Also, I am quite new to using HPC and Slurm, what is the best way to answer yes or no to the script's prompts? 

Thanks in advance for the help.

**Comment by franciscozorrilla** [comment]
Hey Edward, thanks for posting your issues here and sorry for the delay in responding.

Based on the error message it seems like there is some problem related to the the account and/or partition, most likely the latter.

For some background: the metaGEM.sh script is supposed to help configure values/parameters prior to submission, for example by setting the Snakefile target rule (e.g. what tasks should be run) and editing the cluster_config.json file to set e.g. number of cores you want for those jobs. I suggest having a look through the script just to get an idea of what its trying to accomplish, you dont really need to use it if you understand what it is trying to do, but it can sometimes help speed up the setup process before launching jobs by avoiding manual editing of files.

More specifically this is the function that submits jobs to the cluster based on user inputs (see lines 427, 446):

https://github.com/franciscozorrilla/metaGEM/blob/8609ad6bcf040807df0928705d91b0ae31923259/workflow/metaGEM.sh#L369-L454

By default, the cluster_config.json file does not have a partition field, which I see is present in your slurm submission file. I would suggest to verify that your partition is indeed called "nodes", and then add this information to the cluster_config.json file. For example, here is my file:

```
[fz274@login-q-4 full_run]$ paste cluster_config.json 
{
"__default__" : {
        "account" : "MRC-TOX-SL2-CPU",
        "time" : "0-24:00:00",
        "n" : 28,
        "tasks" : 1,
        "mem" : 30G,
        "cpusPerTask" : 1,
        "name"      : "DL.{rule}",
        "output"    : "logs/{wildcards}.%N.{rule}.out.log",
        "part" : "cclake",
},
}
``` 

After adding the "part" field with your specific partition (i.e. replace "cclake" with "nodes"), then you can run the following command on your terminal to launch jobs:

```
nohup snakemake all -j 200 -k --cluster-config cluster_config.json -c "sbatch -A {cluster.account} -p {cluster.part} --mem {cluster.mem} -t {cluster.time} -n {cluster.n} --ntasks {cluster.tasks} --cpus-per-task {cluster.n} --output {cluster.output}" &
```

Please let me know if this works for you. If so, then I will think about updating the metaGEM.sh script and the cluster_config.json files to inlcude the partition options by default.

> Also, I am quite new to using HPC and Slurm, what is the best way to answer yes or no to the script's prompts?

You can simply enter "y" or "n" and press enter.

Best wishes,
Francisco

**Comment by ecairns62** [comment]
Hi Francisco. 

No worries at all. 

Still no luck trying to add in the partition to the config file to avoid the error. However, I've experimented with just setting the cluster parameters in the slurm submission file, and then running the metaGEM.sh script as a local job:

"
#!/bin/bash -l
#SBATCH -D ./                          # Set wd
#SBATCH --export=ALL                   # Copy current enviroment
#SBATCH -J Metagem1DNA                 # Job name
#SBATCH -p nodes                       # Specify partition (e.g., compute, batch)
#SBATCH -N 2                           # Number of nodes
#SBATCH -n 4                           # Number of cores            
#SBATCH -t 2:00:00                     # Time limit hrs:min:sec
#SBATCH -output=metagem_%j.log         # Standard output and error log

#activate env
conda activate metagem

# Run MetaGem
yes | bash metaGEMedit.sh -t fastp -j 2 -l

yes | bash metaGEMedit.sh -t qfilterVis 
"

This seems to have worked? I think the Slurm file is requesting the nodes etc itself, and then is getting confused when the metaGEM command tried to do the same thing again. Is this a viable solution?

Also I'm not sure if our Slurm is set up differently, but we submit a file like above using sbatch, and then we can't interact with the script anymore and just get the output. I've added the "yes |" line, which seems to just answer yes to every time the script needs a prompt. Would this cause any issues later on? I've managed to run the pipeline to abundance running it locally, and I haven't seen any commands to answer "no" to yet (although my local run had its own issues raised in another ticket).

**Comment by franciscozorrilla** [comment]
Hi Edward, 

The local flag was mainly developed for users running on workstations or to test small jobs on the login node. If you are running these jobs on a cluster login node, then the admin people will probably not be very happy with you, plus it will not be practical for long jobs and/or processing large numbers of samples. The expected usage would be that the metaGEM.sh script launches jobs to the cluster scheduler, so you should be able to see them using the `squeue -u <your-username>` command. If I were you, I would ask the cluster admin people for some assistance on how to properly get Snakemake to submit the jobs to the cluster.

I dont think you should have any issues regarding the yes/no questions, those were mainly checkpoints to make the user aware of the config files, inputs, and jobs to be launched.

Best wishes,
Francisco

**Comment by ecairns62** [comment]
Hi Francisco, 

Got it, I'll chat with my cluster support team, thanks for the help.

Many thanks, 

Edward Cairns
