### ISSUE TITLE
error in organizing dataset folder into sample-specific folders

### ISSUE THREAD

**Issue by zoey-rw** [franciscozorrilla/thesis_pipeline#83]
The `organizeData` rule doesn't work on my samples because they have underscores throughout the file names (e.g. "HARV_001-O-20180710-COMP-DNA1_R1.fastq.gz"). A simple fix would be to split the sample names at the last underscore instead of the first underscore.

Original:
```
# Create list of unique sample IDs
        for file in *.gz; do 
            echo $file; 
        done | sed 's/_.*$//g' | sed 's/.fastq.gz//g' | uniq > ID_samples.txt
        echo -e " done.\n $(less ID_samples.txt|wc -l) samples identified.\n"
```
Fixes the problem:
```
# Create list of unique sample IDs
        for file in *.gz; do 
            echo $file; 
        done | sed 's/_[^_]*$//g' | sed 's/.fastq.gz//g' | uniq > ID_samples.txt
        echo -e " done.\n $(less ID_samples.txt|wc -l) samples identified.\n"
```

**Comment by franciscozorrilla** [comment]
Hi Zoey, your suggestion has been implemented in the latest commit (https://github.com/franciscozorrilla/metaGEM/commit/87100d170589713a6dff90f8597bf540e545d97d). 
Really sorry if it caused problems with your data!

Best,
Francisco
